# Generated by Django 5.2 on 2025-04-21 20:06

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(max_length=500, upload_to=apps.products.models.Product.get_upload_path, verbose_name='Imagen')),
                ('is_avaliable', models.BooleanField(default=True, verbose_name='Esta activo')),
                ('product_stock', models.PositiveBigIntegerField(default=0, verbose_name='Cantidad')),
                ('product_price', models.IntegerField(default=0, verbose_name='Precio')),
            ],
        ),
    ]
