# Generated by Django 5.2 on 2025-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.IntegerField(verbose_name='Precio total')),
                ('buyout_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('type_payment_method', models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta Debito'), (2, 'Tarjeta de Credito')], default=1, verbose_name='Tipo de Tarjeta')),
                ('number_card', models.CharField(max_length=16, verbose_name='Numero de Tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='BuyoutProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('product_price', models.IntegerField(verbose_name='Precio por producto')),
            ],
        ),
    ]
