# Generated by Django 5.2 on 2025-04-21 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyouts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyout',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Comprador'),
        ),
        migrations.AddField(
            model_name='buyoutproduct',
            name='buyout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buyouts.buyout', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='buyoutproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto'),
        ),
    ]
