# Generated by Django 5.2 on 2025-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_payment_method', models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta Debito'), (2, 'Tarjeta de Credito')], default=1, verbose_name='Tipo de Tarjeta')),
                ('number_card', models.CharField(max_length=16, verbose_name='Numero de Tarjeta')),
                ('date_card', models.CharField(max_length=5)),
                ('cvv_card', models.CharField(max_length=3)),
            ],
        ),
    ]
